### ISSUE TITLE
As a user, it would be helpful if the google map on each criminal page would show their last known location or some other relevant information.

### ISSUE THREAD

**Issue by AdityaPrasad1** [roshan-dongre/idb#31]

**Comment by rp27537** [comment]
Unfortunately, the last known location is not listed for most criminals. The FBI does have a field for the criminal's hometown, but this field is often imprecise (an entire country) or null. We will continue to associate each criminal with the location of the FBI field office that covers the location where they committed their crimes.

I will close the issue. However, feel free to comment with any further questions or concerns.

**Comment by rp27537** [comment]
Estimated Time: 1 hour
Actual Time: 1 hour
